### ISSUE TITLE
web server error

### ISSUE THREAD

**Issue by tangtang1314** [zhuhr213/HDRNet#1]
when  predict   interaction，error   appear

**Comment by zhuhr213** [comment]
hello @tangtang1314 , we have fixed the errors, plz kindly try again ^ ^
Plus, we recommend trying not to use the salient-map plot function when performing multiple sequences prediction task, as this may slow down the running significantly. We recommend that you use the code we provide in .ipynb file to do the plotting job, which is the same as the plotting process in our webserver.
Enjoy ^ ^

**Comment by tangtang1314** [comment]
三克油
