### ISSUE TITLE
'high_attention_region_recognization.ipynb' is not work.

### ISSUE THREAD

**Issue by JalexDooo** [zhuhr213/HDRNet#3]
Hi,

The `high_attention_region_recognization.ipynb` is not work.

It seems that the parameter `W` is error matrix.

'''
Traceback (most recent call last):
  File "~/HDRNet-master/high_attention_region_recognization.py", line 134, in <module>
    visualize.plot_saliency(X, W, nt_width=100, norm_factor=3, str_null=str_null, outdir="out.png")
  File "~/HDRNet-master/utils/visualize.py", line 131, in plot_saliency
    str_sal = W[4, plot_index].reshape(1,-1)
IndexError: index 4 is out of bounds for axis 0 with size 2
'''

**Comment by JalexDooo** [comment]
`W` seems like this
```python
bert_attention_data = one_hot*bert_attention_data
W = np.concatenate([bert_attention_data, struct_attention_data], axis=0)
```

**Comment by zhuhr213** [comment]
hello @JalexDooo ,

we have fixed this error and uploaded the .ipynb file. Please kindly try it now.

haoran

**Comment by JalexDooo** [comment]
Thanks.
