### ISSUE TITLE
Issue with Bert_model.zip File

### ISSUE THREAD

**Issue by biyueeee** [zhuhr213/HDRNet#4]
Hi Haoran,

I wanted to let you know that I encountered an issue with the Bert_model.zip file. It seems to be corrupted and I'm unable to open it. Could you please check the download link or provide an alternative download path?

Thanks,
Yue

**Comment by zhuhr213** [comment]
> Hi Haoran,
> 
> I wanted to let you know that I encountered an issue with the Bert_model.zip file. It seems to be corrupted and I'm unable to open it. Could you please check the download link or provide an alternative download path?
> 
> Thanks, Yue

Hello @Yue,
Thank you for your interest in our research. We have checked the Bert_model.zip file in figshare [https://doi.org/10.6084/m9.figshare.24132423.v3](https://doi.org/10.6084/m9.figshare.24132423.v3), and we didn't see any problems preventing me from downloading and opening it. Please kindly try this figshare link, and if you are using VPN, please try turn it off. If there are any further problems, please feel free to let us know.

haoran

**Comment by biyueeee** [comment]
> > Hi Haoran,
> > I wanted to let you know that I encountered an issue with the Bert_model.zip file. It seems to be corrupted and I'm unable to open it. Could you please check the download link or provide an alternative download path?
> > Thanks, Yue
> 
> Hello @yue, Thank you for your interest in our research. We have checked the Bert_model.zip file in figshare https://doi.org/10.6084/m9.figshare.24132423.v3, and we didn't see any problems preventing me from downloading and opening it. Please kindly try this figshare link, and if you are using VPN, please try turn it off. If there are any further problems, please feel free to let us know.
> 
> haoran

Hi Haoran,

Thank you very much for getting back to me! The link is working fine. FYI, the file I mentioned that could not be opened was downloaded from your web server (http://www.aibio-lab.com:5050/download_BERT_model).

Best regards,
Yue
