### ISSUE TITLE
Data meaning for clip_data file

### ISSUE THREAD

**Issue by WhiteNan** [zhuhr213/HDRNet#5]
Looking at the clip_data files, I observe 6 different columns, but I am not sure what they mean (see below):
Column 1 = A or B. This may be the positive and negative CLIPseq binding?
Column 2 = sequence
Column 3 = Ensembl transcript ID
Column 4 = icSHAPE scores
Column 5 = ???
Column 6 = ???

Can you provide some explanation what these TSV columns mean?
B	ENST00000389680|76|176|1.12923203455362	ACCCTCTAAATCACCACGATCAAAAGGAACAAGCATCAAGCACGCAGCAATGCAGCTCAAAACGCTTAGCCTAGCCACACCCCCACGGGAAACAGCAGTGA	0.585,0.113,0.139,0.229,0.063,0.352,0.519,0.696,0.7,0.527,0.336,0.475,0.373,0.276,1.0,1.0,1.0,0.405,0.469,0.448,0.515,0.631,0.724,0.911,0.521,0.083,0.177,0.679,0.931,0.933,0.413,0.425,0.102,0.328,0.459,0.358,0.873,0.79,0.47,0.157,0.965,0.994,0.931,0.146,0.235,0.316,0.172,0.982,1.0,1.0,0.32,0.103,0.243,0.99,0.086,0.126,0.295,0.726,0.991,0.714,0.848,0.447,1.0,0.063,0.062,0.172,0.251,0.624,0.204,0.071,0.385,0.783,0.359,0.159,0.092,0.306,0.177,1.0,0.171,0.051,0.101,0.013,0.101,0.649,0.334,0.187,0.005,0.173,0.068,0.421,1.0,0.978,0.532,0.471,0.078,0.13,0.193,0.105,0.15,0.346,0.634	1.12923203455362	1
And I don't understand why the sequences is DNA not RNA. I also did not find any code in the code that converts DNA sequences into RNA sequences.

**Comment by zhuhr213** [comment]
@WhiteNan Sorry for the delay. The sequences are cDNA, synthetic DNA that has been transcribed from a specific mRNA. Column 1 represents the train/valid split. Column 5 is the binding score. Column 6 is the label. All RBP data were collected from https://www.nature.com/articles/s41422-021-00476-y where you can find all details.

**Comment by WhiteNan** [comment]
Thanks for your reply.I would like to know if you convert the cDNA sequence before inputting it into the model, or if you convert it when outputting the final result.I couldn't find specific details about these in the code.I am looking forward to your reply.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhuhr213/HDRNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月21日(星期一) 下午3:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhuhr213/HDRNet] Data meaning for clip_data file (Issue #5)





 
@WhiteNan Sorry for the delay. The sequences are cDNA, synthetic DNA that has been transcribed from a specific mRNA. Column 1 represents the train/valid split. Column 5 is the binding score. Column 6 is the label. All RBP data were collected from https://www.nature.com/articles/s41422-021-00476-y where you can find all details.

**Comment by zhuhr213** [comment]
@WhiteNan Thanks for asking, but mostly you don't have to convert it to RNA, because they all represent the same thing. You just need to keep all the data consistent, not partially transformed to RNA and partially maintained as DNA. In our study we didn't convert it to RNA because the only difference is the T-U transformation. But we convert T to U only in plotting. If you feel confused about transcription, this article might help: https://www.khanacademy.org/science/biology/gene-expression-central-dogma/transcription-of-dna-into-rna/a/stages-of-transcription
@WhiteNan

**Comment by WhiteNan** [comment]
Thank you very much for your reply, which has resolved my confusion.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhuhr213/HDRNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月21日(星期一) 下午3:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhuhr213/HDRNet] Data meaning for clip_data file (Issue #5)





 
@WhiteNan Thanks for asking, but mostly you don't have to convert it to RNA, because they all represent the same thing. You just need to keep all the data consistent, not partially transformed to RNA and partially maintained as DNA. In our study we didn't convert it to RNA because the only difference is the T-U transformation. But we convert T to U only in plotting. If you feel confused about transcription, this article might help: https://www.khanacademy.org/science/biology/gene-expression-central-dogma/transcription-of-dna-into-rna/a/stages-of-transcription
 @WhiteNan
